<?php
// module/Album/view/product/product/index.phtml:

$title = 'My products';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('admin_product_cart', ['action' => 'add']) ?>">Add new product</a>
</p>

<table class="table">
<tr>
	<th>Product</th>
	<th>Cart</th>
	<th>Quantity</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($productcarts as $productcart) : ?>
    <tr>
		<td><?= $this->escapeHtml($productcart->name_product) ?></td>
		<td><?= $this->escapeHtml($productcart->id_cart) ?></td>
		<td><?= $this->escapeHtml($productcart->quantity) ?></td>
		<td>
            <a href="<?= $this->url('admin_product_cart', ['action' => 'edit', 'id' => $productcart->id]) ?>">Edit</a>
            <a href="<?= $this->url('admin_product_cart', ['action' => 'delete', 'id' => $productcart->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>