<?php
// module/Album/view/author/author/index.phtml:

$title = 'My authors';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('admin_author', ['action' => 'add']) ?>">Add new author</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($authors as $author) : ?>
    <tr>
        <td><?= $this->escapeHtml($author->name) ?></td>
		<td>
            <a href="<?= $this->url('admin_author', ['action' => 'edit', 'id' => $author->id]) ?>">Edit</a>
            <a href="<?= $this->url('admin_author', ['action' => 'delete', 'id' => $author->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>