		<!-- Page Title
		============================================= -->

    <!-- Begin Page Content -->
	<div class="container-fluid">

<!-- Page Heading -->
		<div class="d-sm-flex align-items-center justify-content-between mb-4">
			<h1 class="h3 mb-0 text-gray-800">Nos-produits</h1>
		</div>
	</div>
		</section><!-- #page-title end -->
		
					
		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">
					
					<!-- Portfolio Items
					============================================= -->
					<div class="ajax_container">
						
						<?php 
						/*
							foreach($products as $product)
							{
							?>

									<article class="portfolio-item col-md-4 col-sm-6 col-12 <?="pf-".$product->name_color;?> <?="pf-".$product->name_category;?> <?="pf-".$product->name_manufacturer;?> <?="pf-".$product->name_year;?>" >
										<div class="grid-inner">
											<div class="portfolio-image">
												<a href="<?= $this->url('nos-produits', ['action' => 'view', 'id' => $product->id]) ?>">
													<img src="<?="./admin/img/".$product->product_img;?>" alt="Open Imagination">
												</a>
												<div class="bg-overlay">
													<div class="bg-overlay-content dark" data-hover-animate="fadeIn">
														<a href="<?= $this->url('nos-produits', ['action' => 'view', 'id' => $product->id]) ?>" class="overlay-trigger-icon bg-light text-dark" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350"><i class="icon-line-ellipsis"></i></a>
													</div>
													<div class="bg-overlay-bg dark" data-hover-animate="fadeIn"></div>
												</div>
											</div>
											<div class="portfolio-desc">
												<h3><a href="#"><?= $product->name ?></a></h3>
												<span><a href="#">Catégorie: <?= $product->name_category?></a> </span>
												<span><a href="#">Année: <?= $product->name_year?></a></span>
											</div>
										</div>
									</article>
									
									<?php } */ ?>

					</div><!-- #portfolio end -->

				</div>
			</div>
		</section><!-- #content end -->

		