<?php
$title = 'Add new Admin';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Admin name');

// This provides a default CSS class and placeholder text for the password element:
$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('type', 'password');
$password->setAttribute('placeholder', 'Password');
	
// This provides a default CSS class and placeholder text for the email element:
$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');
	
$profil_img = $form->get('profil_img');
$profil_img->setAttribute('class', 'form-control');
$profil_img->setAttribute('type', 'file');
$profil_img->setAttribute('name', 'profil_img');
$profil_img->setAttribute('id', 'profil_img');


// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('admin_admin', ['action' => 'add']));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
<!--
    <label for="file">Image</label>
    <input class="form-control" type="file" name="profil_img" accept="image/png, image/jpeg">
-->
	<?= $this->formLabel($profil_img) ?>
	<?= $this->formElement($profil_img) ?>
    <?= $this->formElementErrors()->render($profil_img, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();