<?php
// module/Album/view/customer/customer/delete.phtml:

$title = 'Delete Admin';
$url   = $this->url('admin_customer', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Etes-vous sûr de vouloir supprimer ce compte ?
    "<?= $this->escapeHtml($customer->name) ?>"
	"<?= $this->escapeHtml($customer->email) ?>" ?
	Tous les paniers lier à ce compte seront supprimer.
	
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $customer->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>