<?php
$title = 'Add new cart';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the customer element:
$customer = $form->get('id_customer');
$customer->setAttribute('class', 'form-control');
$customer->setAttribute('placeholder', 'Author');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('admin_cart', ['action' => 'add']));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>

<div class="form-group">
    <?= $this->formLabel($customer) ?>
    <?= $this->formElement($customer) ?>
    <?= $this->formElementErrors()->render($customer, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();