<?php
// module/Album/view/manufacturer/manufacturer/index.phtml:

$title = 'My manufacturers';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('admin_manufacturer', ['action' => 'add']) ?>">Add new manufacturer</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($manufacturers as $manufacturer) : ?>
    <tr>
        <td><?= $this->escapeHtml($manufacturer->name) ?></td>
		<td>
            <a href="<?= $this->url('admin_manufacturer', ['action' => 'edit', 'id' => $manufacturer->id]) ?>">Edit</a>
            <a href="<?= $this->url('admin_manufacturer', ['action' => 'delete', 'id' => $manufacturer->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>