<?php
$title = 'Add new shoe';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Shoe name');

// This provides a default CSS class and placeholder text for the color element:
$color = $form->get('id_color');
$color->setAttribute('class', 'form-control');
$color->setAttribute('placeholder', 'Color');
	
// This provides a default CSS class and placeholder text for the manufacturer element:
$manufacturer = $form->get('id_manufacturer');
$manufacturer->setAttribute('class', 'form-control');
$manufacturer->setAttribute('placeholder', 'Manufacturer');

$shoe_img = $form->get('shoe_img');
$shoe_img->setAttribute('class', 'form-control');
$shoe_img->setAttribute('type', 'file');
$shoe_img->setAttribute('name', 'shoe_img');
$shoe_img->setAttribute('id', 'shoe_img');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('admin_shoe', ['action' => 'add']));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($color) ?>
    <?= $this->formElement($color) ?>
    <?= $this->formElementErrors()->render($color, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($manufacturer) ?>
    <?= $this->formElement($manufacturer) ?>
    <?= $this->formElementErrors()->render($manufacturer, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
	<?= $this->formLabel($shoe_img) ?>
	<?= $this->formElement($shoe_img) ?>
    <?= $this->formElementErrors()->render($shoe_img, ['class' => 'help-block']) ?>
</div>
<br>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();