<?php
// module/Album/view/admin/shoe/delete.phtml:

$title = 'Delete shoe';
$url   = $this->url('admin_shoe', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($shoe->name) ?>",
	"<?= $colors[$shoe->id_color]['name']; ?>",
	"<?= $manufacturers[$shoe->id_manufacturer]['name']; ?>"
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $shoe->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>