<?php
// module/Album/view/product/product/index.phtml:

$title = 'My products';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('admin_product', ['action' => 'add']) ?>">Add new product</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Author</th>
	<th>Year</th>
	<th>Color</th>
	<th>Manufacturer</th>
	<th>Category</th>
	<th>Image</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($products as $product) : ?>
    <tr>
        <td><?= $this->escapeHtml($product->name) ?></td>
		<td><?= $this->escapeHtml($product->name_author) ?></td>
		<td><?= $this->escapeHtml($product->name_year) ?></td>
		<td><?= $this->escapeHtml($product->name_color) ?></td>
		<td><?= $this->escapeHtml($product->name_manufacturer) ?></td>
		<td><?= $this->escapeHtml($product->name_category) ?></td>
		<td><img src="<?="./admin/img/".$product->product_img;?>"></td>
		<td>
            <a href="<?= $this->url('admin_product', ['action' => 'edit', 'id' => $product->id]) ?>">Edit</a>
            <a href="<?= $this->url('admin_product', ['action' => 'delete', 'id' => $product->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>